### ISSUE TITLE
Error in pokemon encounter Pokemon instance has no attribute '__getitem__'

### ISSUE THREAD

**Issue by TheWayAway** [j-e-k/poketrainer#280] opened 2016-07-30 00:21 UTC
This is my inventory data:

```
2016-07-29 17:16:45,159 [    pgoapi] [ INFO] Player Items Before Cleanup: PokeBalls: 34, GreatBalls: 40, MasterBalls: 0, UltraBalls: 23 
 Potion: 24, Super Potion: 9, Max Potion 4, Hyper Potion 32, Lucky Eggs 4
2016-07-29 17:16:45,160 [    pgoapi] [ INFO] Intentory has 243/350 items
2016-07-29 17:16:45,233 [    pgoapi] [ INFO] Player Inventory after cleanup: PokeBalls: 34, GreatBalls: 40, MasterBalls: 0, UltraBalls: 23 
 Potion: 24, Super Potion: 9, Max Potion 4, Hyper Potion 32, Lucky Eggs 4
```

And I'm getting the following error:
```
2016-07-29 17:18:05,171 [    pgoapi] [ERROR] Error in pokemon encounter Pokemon instance has no attribute '__getitem__'
2016-07-29 17:18:10,176 [    pgoapi] [ INFO] =================================
2016-07-29 17:18:10,176 [    pgoapi] [ INFO] On my way to the next fort! :) Traveled 293.55 meters of 467.17 
2016-07-29 17:18:10,176 [    pgoapi] [ INFO] Travel Link: ##REMOVED##
2016-07-29 17:18:10,250 [    pgoapi] [ INFO] Player Info: GottaCatch, Currencies: POKECOIN: 10,STARDUST: 252443, Pokemon Caught in this run: 0
2016-07-29 17:18:11,398 [    pgoapi] [ INFO] Nearby Pokemon: Oddish
2016-07-29 17:18:11,514 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Nickname: , Type: Oddish, CP: 0, IV: 0.0
2016-07-29 17:18:11,669 [    pgoapi] [ INFO] Couldn't catch Nickname: , Type: NA, CP: 0, IV: 0.0 Your pokemon bag was full, attempting to clear and re-try
2016-07-29 17:18:11,869 [    pgoapi] [ERROR] Error in pokemon encounter Pokemon instance has no attribute '__getitem__'
```
This error is currently looping for me.

**Comment by Myhorta** [comment] 2016-07-30 00:36
> Your pokemon bag was full, attempting to clear and re-try

The bot can't catch without space in the inventory.

**Comment by infinitewarp** [comment] 2016-07-30 01:32
True, but there's still a bug here because that error shouldn't be triggered; that line is only generated from an unhandled exception. If the bag is full, the code is supposed to `cleanup_pokemon` and if `retry` is enabled recursively keep calling `disk_encounter_pokemon` until something succeeds. I'll improve the logging and try reproducing this issue.

**Comment by infinitewarp** [comment] 2016-07-30 01:44
I just created a new branch in my fork that added noisier exception logging. If you want to try running https://github.com/infinitewarp/poketrainer/tree/logging, you should get more info that should help narrow down the exact problem.

**Comment by infinitewarp** [comment] 2016-07-30 06:44
I managed to fill up both my item bag and pokémon bag, but I'm unable to reproduce this issue on my latest pull request branches. I suspect that another revent commit against the develop branch may have resolved this.

In my case:
```
2016-07-30 02:43:06,393 [    pgoapi] [ INFO] Nearby Pokemon: Paras
2016-07-30 02:43:06,630 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Paras CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 20, Score: 0, IV-Norm.: 0
2016-07-30 02:43:06,887 [    pgoapi] [ INFO] Couldn't catch Paras Your pokemon bag was full, attempting to clear and re-try
2016-07-30 02:43:07,548 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Paras CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 20, Score: 0, IV-Norm.: 0
2016-07-30 02:43:07,799 [    pgoapi] [ INFO] Couldn't catch Paras Your pokemon bag was full, attempting to clear and re-try
```

**Comment by TheWayAway** [comment] 2016-07-30 06:47
Thanks for looking into it.  I'll update again (unfortunately on Monday) and I'll let you know if I run into it again.

**Comment by cod3b0t** [comment] 2016-08-02 02:54
I can also confirm that the inventory isnt clearing up for the items bag, This is what i get.
```
2016-08-01 22:50:09,277 [    pgoapi] [ INFO] Player Items Before Cleanup: PokeBalls: 0, GreatBalls: 0, MasterBalls: 0, UltraBalls: 0 
 Potion: 136, Super Potion: 20, Max Potion 0, Hyper Potion 0, Lucky Eggs 0, Razz Berries 83
2016-08-01 22:50:09,277 [    pgoapi] [ INFO] Inventory has 351/350 items
2016-08-01 22:50:10,267 [    pgoapi] [ INFO] Player Inventory after cleanup: PokeBalls: 0, GreatBalls: 0, MasterBalls: 0, UltraBalls: 0 
 Potion: 136, Super Potion: 20, Max Potion 0, Hyper Potion 0, Lucky Eggs 0, Razz Berries 83

```

**Comment by rirze** [comment] 2016-08-02 03:00
@cod3b0t It seems you've run out of space for any pokeballs, meaning that you can't use berries or collect pokemon. You should set limits on how many potions, revives, and berries your bot can carry. That way, it can recycle them and have space for pokeballs.

**Comment by cod3b0t** [comment] 2016-08-02 05:27
@rirze where should i change it ? Is it on the config.json file?

**Comment by destiny117** [comment] 2016-08-02 08:06
I will close this as it the original issue seems to be fixed.

@cod3b0t yes plese check the config.json.example on how to set min-items. Open a new issue if you need help

**Closed by destiny117** 2016-08-02 08:06 UTC
