### ISSUE TITLE
latest bot has seriously problem with back origin

### ISSUE THREAD

**Issue by loveinpin** [j-e-k/poketrainer#391] opened 2016-08-02 12:46 UTC
Bot 1    API key1    Disneyland CA   45min 
Bot 2   API key2    Sydney  NSW     33min 
Bot 3   API key3    Newport Pier      47min

3  different location    Same set   Same commit    seems all get in return loop  
need 2 shut it down Manually  then restart  login to solve this issue

[    pgoapi] [ INFO] No more spinnable forts within proximity. Returning back to origin
[    pgoapi] [ INFO] ===============================================
[    pgoapi] [ INFO] Total trip distance will be: 0.00 meters

**Comment by destiny117** [comment] 2016-08-02 12:53
latest dev branch will automatically restart the bot if this happens, the source of the problem is unknkown though. I guess it's either the session that is no longer valid (or would have to be renewed somehow?) or it's a rate limit that will only reset with a new session

can you verify the newset release does auto-restart?

**Comment by loveinpin** [comment] 2016-08-02 13:15
I already rewrite the file from newest dev after get this problem, bt the bot still running loop when it needs return to origin, it won't auto-restart by itself.

**Comment by destiny117** [comment] 2016-08-02 13:19
you sure you are running the lastest dev release including 4235103df4d67b27e6bcb6a51f8f4db70a08d4c2 (1 hour old) ?

**Comment by rirze** [comment] 2016-08-02 15:31
Try changing
```
"STAY_WITHIN_PROXIMITY": 9999,
```
to a higher value. I'm not quite sure that this option is still implemented, but increasing this could help too:
```
"SKIP_VISITED_FORT_DURATION": 600,
```

**Comment by djadstar** [comment] 2016-08-03 20:31
I'm having the same issue, even after the latest release.

**Comment by jolbol1** [comment] 2016-08-03 20:44
Same Here Now :(

**Comment by rirze** [comment] 2016-08-03 21:50
The API has officially changed, so all bots (not just this repo) are not receiving any information from the server at the moment.

**Comment by stolencatkarma** [comment] 2016-08-04 00:23
This is a known issue with the API and is being worked on. closing this.

**Closed by stolencatkarma** 2016-08-04 00:23 UTC
Labels: bug
