### ISSUE TITLE
[ERROR] Error in main loop 'GET_MAP_OBJECTS`

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#290] opened 2016-07-30 03:46 UTC
Ref #225 
Still occurs, but less frequent
```
2016-07-29 21:30:05,401 [   pokecli] [ERROR] Error in main loop 'GET_MAP_OBJECTS', restarting at location: (39.54835262692445, -105.00084969203148, 0)
Traceback (most recent call last):
  File "pokecli.py", line 158, in main
    api.main_loop()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 996, in main_loop
    self.spin_all_forts_visible()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 484, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 401, in walk_to
    while self.catch_near_pokemon() and catch_attempt <= self.max_catch_attempts:
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 521, in catch_near_pokemon
    map_cells = self.nearby_map_objects()['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
```

**Comment by infinitewarp** [comment] 2016-07-30 06:40
I think I see where the problem is. I don't have a way of reproducing the condition you've hit, but I think this should fix it.

**Comment by infinitewarp** [comment] 2016-07-30 16:47
Since my pull request was merged, @HibikiFox would you see if this is still happening for you?

**Comment by djadstar** [comment] 2016-07-30 20:50
I'm currently having a similar issue, not sure if it's related?: 

` No fort to walk to! {'responses': {'GET_MAP_OBJECTS': {'status': 1, 'map_cells': [{'s2_cell_id': 9926593883775434752L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594308977197056L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926593890217885696L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926593892365369344L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594304682229760L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594306829713408L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926593913840205824L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926593915987689472L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594326157066240L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594328304549888L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594330452033536L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594332599517184L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594321862098944L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594324009582592L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594345484419072L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594347631902720L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594334747000832L, 'current_timestamp_ms': 1469911804557L}, {'s2_cell_id': 9926594336894484480L, 'current_timestamp_ms': 1469911804557L}]}}, 'status_code': 1, 'auth_ticket': {'expire_timestamp_ms': 1469913604557L, 'start': 'LHcma/LJXfxnhdbKarCKPHpLYvpfRb5dH9MZ3ayFiQGfJUBpA4E+jJ1mbcBMN4Bz8AVpD4CZnQ6xFXye8dxQzDsd8npxSxZ2LKwL8LqSndA=', 'end': 'gJoKXm9Gw3CwUDb4vuRjlg=='}, 'request_id': 8145806132888207460L}`

**Comment by HibikiFox** [comment] 2016-07-31 00:06
@infinitewarp 
I am getting only this one now

```
2016-07-30 17:57:48,737 [   pokecli] [ERROR] Error in main loop 'RECYCLE_INVENTORY_ITEM', restarting at location: (39.54720005679049, -104.99696992855397, 0)
Traceback (most recent call last):
  File "pokecli.py", line 158, in main
    api.main_loop()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 1006, in main_loop
    self.spin_all_forts_visible()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 491, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 405, in walk_to
    self.spin_nearest_fort()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 431, in spin_nearest_fort
    self.walk_to_fort(destinations[0], directly=True)
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 502, in walk_to_fort
    self.walk_to((fort['latitude'], fort['longitude']), directly=directly)
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 401, in walk_to
    self.heartbeat()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 312, in heartbeat
    self.log.debug(self.cleanup_inventory(self.inventory.inventory_items))
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 618, in cleanup_inventory
    'RECYCLE_INVENTORY_ITEM']
KeyError: 'RECYCLE_INVENTORY_ITEM'
```
I will open A new issue

**Comment by albertonoys** [comment] 2016-07-31 00:44
I'm getting the one that @djadstar is getting too. It's not a bug but I don't know why this:

`self.log.info("No fort to walk to! %s", res)`

It's not like this:
```
self.log.info("No fort to walk to!)
self.log.debug("No fort to walk to! %s", res)
```

**Closed** 2016-07-31 21:46 UTC
