### ISSUE TITLE
Crashes on login. (Python 3)

### ISSUE THREAD

**Issue by BoBeR182** [j-e-k/poketrainer#427] opened 2016-08-07 08:52 UTC
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/home/bober/poketrainer/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/home/bober/poketrainer/pgoapi/pgoapi.py", line 271, in call
    response = request.request(self.get_api_endpoint(), self._req_method_list[id(gevent.getcurrent())], player_position)
  File "/home/bober/poketrainer/pgoapi/rpc_api.py", line 129, in request
    request_proto = self._build_main_request(subrequests, player_position)
  File "/home/bober/poketrainer/pgoapi/rpc_api.py", line 200, in _build_main_request
    sig.location_hash1 = generateLocation1(ticket_serialized, request.latitude, request.longitude, request.altitude)
  File "/home/bober/poketrainer/pgoapi/utilities.py", line 171, in generateLocation1
    locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
  File "/home/bober/poketrainer/pgoapi/utilities.py", line 192, in d2h
    return hex.decode("hex")
AttributeError: 'str' object has no attribute 'decode'

**Comment by BoBeR182** [comment] 2016-08-07 08:57
https://github.com/keyphact/pgoapi/commit/6b50289299f7517efb1d2ed184cc2dd774c3e60e

**Comment by Abdess** [comment] 2016-08-07 12:44
Crash on login too but with a different traceback:


> 2016-08-07 14:43:24,594 [   pokecli] [ INFO] Your given location: Gapstow Bridge, New York, NY 10019, USA
> 2016-08-07 14:43:24,595 [   pokecli] [ INFO] lat/long/alt: 40.766933 -73.9738095 0.0
> Traceback (most recent call last):
>   File "pokecli.py", line 179, in <module>
>     main()
>   File "pokecli.py", line 147, in main
>     data = json.loads(data.encode() if len(data) > 0 else '{}')
>   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
>     raise ValueError(errmsg("Extra data", s, end, len(s)))
> ValueError: Extra data: line 3 column 2 - line 6 column 2 (char 43 - 152)

**Comment by infinitewarp** [comment] 2016-08-07 16:21
Actually, it looks like there bay be some other Python 3 regressions also caused by the recent merge of the unknown6 fixes. For now, please try again with Python 2.7.

**Comment by infinitewarp** [comment] 2016-08-07 17:28
Should be fixed now on the develop branch.

**Closed by infinitewarp** 2016-08-07 17:28 UTC
Labels: bug
