### ISSUE TITLE
[ERROR] Web.py 

### ISSUE THREAD

**Issue by rhythem** [j-e-k/poketrainer#302] opened 2016-07-30 16:46 UTC
I am facing this error:
```
rhythem:~/workspace/poketrainer (develop) $ sudo python web.py
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 368-674-423
10.240.0.33 - - [30/Jul/2016 16:45:53] "GET /amit7493@gmail.com/pokemon HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 95, in pokemon
    s = get_api_rpc(username)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 42, in get_api_rpc
    with open(desc_file) as f:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/workspace/poketrainer/.listeners'
10.240.0.136 - - [30/Jul/2016 16:45:54] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
10.240.0.230 - - [30/Jul/2016 16:45:54] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.240.0.212 - - [30/Jul/2016 16:45:54] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.240.0.33 - - [30/Jul/2016 16:45:56] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
10.240.0.157 - - [30/Jul/2016 16:45:56] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
10.240.0.214 - - [30/Jul/2016 16:45:58] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```
Can someone help?

**Comment by Myhorta** [comment] 2016-07-30 16:58
You need to be running the bot. 
If you are running bot, maybe your pokecli.py and web.py are not in the same folder?  The pokecli.py script creates the file .listeners when its current directory.

**Comment by rhythem** [comment] 2016-07-30 17:00
Ok my bad, the bot is running now but this is comming:

`rhythem:~/workspace/poketrainer (develop) $ sudo python web.py
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 368-674-423
10.240.1.16 - - [30/Jul/2016 17:00:07] "GET /amit7493@gmail.com/pokemon HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 95, in pokemon
    s = get_api_rpc(username)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 51, in get_api_rpc
    c.connect("tcp:/127.0.0.1:%i" % sock_port)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/socket.py", line 40, in connect
    return self._events.connect(endpoint, resolve)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/events.py", line 301, in connect
    r.append(self._socket.connect(endpoint_))
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/gevent_zmq.py", line 102, in connect
    return super(Socket, self).connect(*args, **kwargs)
  File "zmq/backend/cython/socket.pyx", line 528, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:5636)
    
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7835)
    
ZMQError: Invalid argument
10.240.0.214 - - [30/Jul/2016 17:00:08] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
10.240.0.230 - - [30/Jul/2016 17:00:08] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.240.0.212 - - [30/Jul/2016 17:00:08] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.240.0.214 - - [30/Jul/2016 17:00:09] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
10.240.0.212 - - [30/Jul/2016 17:00:09] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
10.240.1.16 - - [30/Jul/2016 17:00:12] "GET /amit7493@gmail.com/pokemon HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 95, in pokemon
    s = get_api_rpc(username)
  File "/home/ubuntu/workspace/poketrainer/web.py", line 51, in get_api_rpc
    c.connect("tcp:/127.0.0.1:%i" % sock_port)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/socket.py", line 40, in connect
    return self._events.connect(endpoint, resolve)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/events.py", line 301, in connect
    r.append(self._socket.connect(endpoint_))
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/gevent_zmq.py", line 102, in connect
    return super(Socket, self).connect(*args, **kwargs)
  File "zmq/backend/cython/socket.pyx", line 528, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:5636)
    
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7835)
    
ZMQError: Invalid argument
10.240.1.12 - - [30/Jul/2016 17:00:12] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
10.240.1.16 - - [30/Jul/2016 17:00:12] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.240.1.12 - - [30/Jul/2016 17:00:12] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
10.240.0.214 - - [30/Jul/2016 17:00:12] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.240.1.12 - - [30/Jul/2016 17:00:15] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
10.240.0.213 - - [30/Jul/2016 17:00:15] "GET /amit7493@gmail.com/pokemon?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
`

**Comment by rirze** [comment] 2016-07-30 17:05
What is the exact url you are trying to access? That would help us figure what the `invalid argument` is.
Also could you try without running sudo? It may or may not help.

**Comment by rhythem** [comment] 2016-07-30 17:06
I am running it with sudo. 
I have the code hosted on c9users.io. 
https://gruntsetup-rhythem.c9users.io/amit7493@gmail.com

**Comment by rhythem** [comment] 2016-07-30 17:22
Any help guys??? @Myhorta  @rirze

**Comment by Myhorta** [comment] 2016-07-30 17:28
hmm.. ok. You are most likely hitting the firewall. [docs](https://docs.c9.io/docs/multiple-ports)
You can try to force to one of the available but doubt it will work.

**Comment by rhythem** [comment] 2016-07-30 17:30
The master branch was working but this does not seems to work. master and develop are two different spaces. So they would be different links. hence ports should not be a problem.

**Comment by Myhorta** [comment] 2016-07-30 17:33
The thing is, in the master the bot writes to a file and the web.py reads from there.
In the dev. the bot and the web.py share a socket connection to pass data around.

**Comment by rhythem** [comment] 2016-07-30 17:34
Ah i get it, so the bot is already using the port 8080 ? if i make a new port 8081 and run web.py there should it work?

**Comment by Myhorta** [comment] 2016-07-30 17:39
That is for external addresses. 
The connection between the bot and the web.py is trough the localhost(127.0.0.1), the port is asked to the kernel, it is not hardcoded. I don't know what policy c9 adopts for localhost ports.

You can try to force it to use a external address thought. Ask for instructions if you don't know how.

**Comment by rhythem** [comment] 2016-07-30 17:41
Ok i dont know how? Ask C9 ? or you guys?

**Comment by Myhorta** [comment] 2016-07-30 17:51
Try to replace pokecli.py@147
`s.bind("tcp://127.0.0.1:%i" % sock_port) # the free port should still be the same`
to
`s.bind("tcp://*:8081")`
and web.py@51
` c.connect("tcp://127.0.0.1:%i" % sock_port)`
to
` c.connect("tcp://gruntsetup-rhythem.c9users.io/amit7493@gmail.com:8081")`

**Comment by rhythem** [comment] 2016-07-30 17:56
`2016-07-30 17:55:48,585 [   pokecli] [ INFO] Your given location: The Embarcadero & Beach St, San Francisco, CA 94133, USA
2016-07-30 17:55:48,585 [   pokecli] [ INFO] lat/long/alt: 37.8081388 -122.4096138 0.0
Traceback (most recent call last):
  File "pokecli.py", line 171, in <module>
    main()
  File "pokecli.py", line 133, in main
    s.bind("tcp://*:8081")  # let the kernel find a free port
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: getsockaddrarg: AF_INET address must be tuple, not str`

**Comment by rhythem** [comment] 2016-07-30 17:58
wait i am sorry i replace it at wrong line. however after correct replacement this comes: 
```
``rhythem:~/workspace/poketrainer (develop) $ python pokecli.py -i 0
2016-07-30 17:58:01,972 [   pokecli] [ INFO] Your given location: The Embarcadero & Beach St, San Francisco, CA 94133, USA
2016-07-30 17:58:01,972 [   pokecli] [ INFO] lat/long/alt: 37.8081388 -122.4096138 0.0
Traceback (most recent call last):
  File "pokecli.py", line 171, in <module>
    main()
  File "pokecli.py", line 147, in main
    s.bind("tcp://*:8081") # the free port should still be the same
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/socket.py", line 43, in bind
    return self._events.bind(endpoint, resolve)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/events.py", line 308, in bind
    r.append(self._socket.bind(endpoint_))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5319)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7835)
zmq.error.ZMQError: Address already in use
```

**Comment by Myhorta** [comment] 2016-07-30 18:04
Something is already running in that port. Maybe the apache server? Do you have access to the terminal? 
type `netstat -tulpn` and kill what is running at that port, if killing is an option.

**Comment by rhythem** [comment] 2016-07-30 18:07
I restarted. Now the bot is working fine. however the web.py shows this:
```
Traceback (most recent call last):
  File "web.py", line 127, in <module>
    app.run(host='0.0.0.0', debug=True,port=8081)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 677, in run_simple
    s.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by Myhorta** [comment] 2016-07-30 18:10
The web.py need 2 ports, one to communicate with the bot and another one to display the info for you. It can't be the same.
Try to put the web.py at 8080 or smth
`    app.run(host='0.0.0.0', debug=True,port=8080)`

**Comment by rhythem** [comment] 2016-07-30 18:12
looks like it throws the same error 

http://pastebin.com/9PSjFVjG

**Comment by Myhorta** [comment] 2016-07-30 18:39
Sorry I'm out of ideas.

**Comment by rhythem** [comment] 2016-07-30 18:42
it's ok no problem!

**Comment by j-e-k** [comment] 2016-07-30 19:22
Will take a look when I get home
Thanks!

**Comment by rhythem** [comment] 2016-07-31 16:29
@j-e-k  were you able to figure this out? i did some research but my limitation in python dint yeild much result!!
TIA for this great bot.

**Comment by j-e-k** [comment] 2016-07-31 20:48
I can't really reproduce this locally. Can you give it a shot in the docker container and see if it works there? This is a networking issue....

**Comment by rhythem** [comment] 2016-07-31 21:30
can you help me with the docker container. i dont understand exactly wht to do!!

**Comment by infinitewarp** [comment] 2016-07-31 21:55
Closing this since in #349 it looks like you managed to get things running. 👍

**Closed by infinitewarp** 2016-07-31 21:55 UTC
Labels: help wanted
