### ISSUE TITLE
Cannot evolve second evolution pokemon

### ISSUE THREAD

**Issue by beeedy** [j-e-k/poketrainer#466] opened 2016-08-09 05:32 UTC
The current system appears to not allow a user to evolve second stage pokemon, throwing an error. In this example Metapod was obviously used, but pulling family based only off the name does not seem like the best method here. I do not know enough about the newish system to know how to easily remedy this

```
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 127, in main
    api = PGoApi(config)
  File "/home/xxxxxxxx/Desktop/poketrainer/pgoapi/pgoapi.py", line 136, in __init__
    self.POKEMON_EVOLUTION_FAMILY[getattr(Enums_pb2, k)] = getattr(Enums_pb2, "FAMILY_" + k)
AttributeError: 'module' object has no attribute 'FAMILY_METAPOD'

```

**Comment by q32103940** [comment] 2016-08-09 12:24
duplicate of #287

**Comment by beeedy** [comment] 2016-08-09 12:42
Wow, I even commented a few times on that one.... For some reason I thought this had been remedied! My apologies

**Closed** 2016-08-12 19:26 UTC
