### ISSUE TITLE
Not Evolving Pokemon Again?

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/poketrainer#452] opened 2016-08-08 04:52 UTC
I have the latest pull and have it configured like I usually did, and it's releasing pokemon, but it doesnt seem to be attempting to evolve, even though I have plenty of candy, here is my config.

`{
  "accounts": [
    {
      "auth_service": "google",
      "username": "XXXXXXXX@gmail.com",
      "password": "XXXXXXXX",
      "location": "XXXXXXXXX",
      "GMAPS_API_KEY": "XXXXXXX",
      "BEHAVIOR": {
        "USE_GOOGLE": true,
        "STEP_SIZE": 75,
        "WANDER_STEPS": 0,
        "EXPERIMENTAL": true,
        "SKIP_VISITED_FORT_DURATION": 600,
        "SPIN_ALL_FORTS": true,
        "STAY_WITHIN_PROXIMITY": 9999,
        "AUTO_USE_LUCKY_EGG": false,
        "EXTRA_WAIT" : 0.3,
        "SLEEP_MULT" : 1.5
      },
      "CAPTURE": {
        "CATCH_POKEMON": true,
        "MIN_FAILED_ATTEMPTS_BEFORE_USING_BERRY": 3,
        "MAX_CATCH_ATTEMPTS": 5,
        "USE_POKEBALL_IF_PERCENT": 15,
        "USE_GREATBALL_IF_PERCENT": 15,
        "USE_ULTRABALL_IF_PERCENT": 15,
        "USE_MASTERBALL": false
      },
      "EGG_INCUBATION": {
        "ENABLE": true,
        "USE_DISPOSABLE_INCUBATORS": true,
        "BIG_EGGS_FIRST": true
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE": 12,
"RATTATA": 50,
"DODUO": 50,
"CATERPIE": 12,
"GOLDEEN": 50,
"PARAS": 50,
"VENONAT": 50,
"ZUBAT": 50,
"HORSEA": 50,
"STARYU": 50

      },
      "POKEMON_CLEANUP": {
        "TESTING_MODE": false,
        "MIN_SIMILAR_POKEMON": 1,
        "MAX_SIMILAR_POKEMON": 999,
        "KEEP_POKEMON_NAMES": ["MEWTWO", "DRATINI"],
        "THROW_POKEMON_NAMES": ["PIDGEOTTO", "KAKUNA", "METAPOD", "SEAKING", "STARMIE", "SEADRA", "PARASECT", "GOLBAT", "VENOMOTH", "DODRIO", "RATICATE", "PINSIR", "GOLDUCK"],
        "RELEASE_METHOD": "CLASSIC",
        "RELEASE_METHOD_CLASSIC": {
          "KEEP_CP_OVER": 1000,
          "KEEP_IV_OVER": 90
        },
        "RELEASE_METHOD_MULTI": {
          "MULTI_DEFAULT_RELEASE_METHOD": "CLASSIC",
          "RELEASE_METHOD_CLASSIC": {
            "KEEP_IV_OVER": 90
          },
          "POKEMON_CONFIGS": {
            "PIDGEOTTO": {
              "RELEASE_METHOD": "CLASSIC",
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000,
                "KEEP_IV_OVER": 90
              }
            },
            "RATICATE": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000
              }
            },
            "PINSIR": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000
              }
            },
            "EEVEE": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 800,
                "KEEP_IV_OVER": 90
              }
            }
          }
        },
        "RELEASE_METHOD_DUPLICATES": {
          "RELEASE_DUPLICATES_MAX_SCORE": 1000,
          "RELEASE_DUPLICATES_SCALAR": 0.9
        },
        "RELEASE_METHOD_ADVANCED": {
          "ALWAYS_RELEASE_BELOW_LEVEL": 0,
          "KEEP_CP_OVER": 1500,
          "KEEP_IV_OVER": 90,
          "BEST_CP": {
            "MIN_AMOUNT": 1,
            "KEEP_ADDITIONAL_SCALAR": 1.0,
            "MAX_AMOUNT": 999
          },
          "BEST_IV": {
            "MIN_AMOUNT": 1,
            "KEEP_ADDITIONAL_SCALAR": 1.0,
            "MAX_AMOUNT": 999,
            "IGNORE_BELOW": 50
          }
        },
        "SCORE_METHOD": "IV",
        "SCORE_METHOD_FANCY": {
          "WEIGHT_IV": 0.5,
          "WEIGHT_LVL": 0.5
        }
      },
      "MIN_ITEMS": {
        "ITEM_POTION": 0,
        "ITEM_SUPER_POTION": 0,
        "ITEM_HYPER_POTION": 0,
        "ITEM_MAX_POTION": 100,
        "ITEM_POKE_BALL": 100,
        "ITEM_GREAT_BALL": 100,
        "ITEM_ULTRA_BALL": 100,
        "ITEM_RAZZ_BERRY": 50,
        "ITEM_REVIVE": 0,
        "ITEM_MAX_REVIVE": 100
      },
      "NEEDY_ITEM_FARMING": {
        "ENABLE": false,
        "POKEBALL_CONTINUE_THRESHOLD": 50,
        "POKEBALL_FARM_THRESHOLD": 10,
        "FARM_IGNORE_POKEBALL_COUNT": false,
        "FARM_IGNORE_GREATBALL_COUNT": false,
        "FARM_IGNORE_ULTRABALL_COUNT": false,
        "FARM_IGNORE_MASTERBALL_COUNT": true,
        "FARM_OVERRIDE_STEP_SIZE": -1
      },
      "CONSOLE_OUTPUT": {
        "LIST_POKEMON_BEFORE_CLEANUP": true,
        "LIST_INVENTORY_BEFORE_CLEANUP": true
      }
    },
    {
      "auth_service": "ptc",
      "username": "someusername",
      "password": "password",
      "location": "University of Southern California, Los Angeles, CA",
      "BEHAVIOR": {
        "USE_GOOGLE": false
      }
    }
  ],
  "defaults": {
      "_info": "copy values to this section to use them for all accounts",
      "_info2": "account settings will always override defaults"
  }
}`

**Comment by j-e-k** [comment] 2016-08-08 04:55
I think a fix on dev just got pushed by @infinitewarp not too long ago, but I could be mistaken

**Comment by freakyfreak87** [comment] 2016-08-08 05:17
I just downloaded the latest pull about an hour ago, so if it was pushed, it doesnt seem fixed, i'll watch my cmd window to double check

**Comment by infinitewarp** [comment] 2016-08-08 05:29
Just to sanity-check, about the ones it's transferring instead of evolving: are they in your POKEMON_EVOLUTION config? Only the types listed there will be evolved.

I *just* fetched and rebased my local copy of develop, and it seems to be working fine for me for pokemon I have defined in my POKEMON_EVOLUTION configs.

```
2016-08-08 01:27:51,954 [    pgoapi] [ INFO] Evolving pokemon: Type: Eevee CP: 578, IV: 93.33, Lvl: 19.0, LvlWild: 19.0, MaxCP: 807, Score: 578, IV-Norm.: 95
2016-08-08 01:27:52,940 [    pgoapi] [ INFO] Evolved to Type: Vaporeon CP: 1516, IV: 93.33, Lvl: 19.0, LvlWild: 19.0, MaxCP: 2114, Score: 1516, IV-Norm.: 94
```

**Comment by freakyfreak87** [comment] 2016-08-08 05:31
`"POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE": 12,
"RATTATA": 50,
"DODUO": 50,
"CATERPIE": 12,
"GOLDEEN": 50,
"PARAS": 50,
"VENONAT": 50,
"ZUBAT": 50,
"HORSEA": 50,
"STARYU": 50,
"SPEAROW":50,
"PSYDUCK":50`

yeah and all of the listed pokemon have plenty of candy to evolve

**Comment by freakyfreak87** [comment] 2016-08-08 05:37
Could any of my config after the evolution portion be counter acting the evolve command?

`},
      "CAPTURE": {
        "CATCH_POKEMON": true,
        "MIN_FAILED_ATTEMPTS_BEFORE_USING_BERRY": 3,
        "MAX_CATCH_ATTEMPTS": 5,
        "USE_POKEBALL_IF_PERCENT": 15,
        "USE_GREATBALL_IF_PERCENT": 15,
        "USE_ULTRABALL_IF_PERCENT": 15,
        "USE_MASTERBALL": false
      },
      "EGG_INCUBATION": {
        "ENABLE": true,
        "USE_DISPOSABLE_INCUBATORS": true,
        "BIG_EGGS_FIRST": true
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE": 12,
"RATTATA": 50,
"DODUO": 50,
"CATERPIE": 12,
"GOLDEEN": 50,
"PARAS": 50,
"VENONAT": 50,
"ZUBAT": 50,
"HORSEA": 50,
"STARYU": 50,
"SPEAROW": 50,
"PSYDUCK": 50
      },
      "POKEMON_CLEANUP": {
        "TESTING_MODE": false,
        "MIN_SIMILAR_POKEMON": 1,
        "MAX_SIMILAR_POKEMON": 999,
        "KEEP_POKEMON_NAMES": ["MEWTWO", "DRATINI"],
        "THROW_POKEMON_NAMES": ["PIDGEOTTO", "KAKUNA", "METAPOD", "SEAKING", "STARMIE", "SEADRA", "PARASECT", "GOLBAT", "VENOMOTH", "DODRIO", "RATICATE", "PINSIR", "GOLDUCK", "FEAROW"],
        "RELEASE_METHOD": "CLASSIC",
        "RELEASE_METHOD_CLASSIC": {
          "KEEP_CP_OVER": 1000,
          "KEEP_IV_OVER": 90
        },
        "RELEASE_METHOD_MULTI": {
          "MULTI_DEFAULT_RELEASE_METHOD": "CLASSIC",
          "RELEASE_METHOD_CLASSIC": {
            "KEEP_IV_OVER": 90
          },
          "POKEMON_CONFIGS": {
            "PIDGEOTTO": {
              "RELEASE_METHOD": "CLASSIC",
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000,
                "KEEP_IV_OVER": 90
              }
            },
            "RATICATE": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000
              }
            },
            "PINSIR": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 2000
              }
            },
            "EEVEE": {
              "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 800,
                "KEEP_IV_OVER": 90
              }
            }
          }
        },
        "RELEASE_METHOD_DUPLICATES": {
          "RELEASE_DUPLICATES_MAX_SCORE": 1000,
          "RELEASE_DUPLICATES_SCALAR": 0.9
        },
        "RELEASE_METHOD_ADVANCED": {
          "ALWAYS_RELEASE_BELOW_LEVEL": 0,
          "KEEP_CP_OVER": 1500,
          "KEEP_IV_OVER": 90,
          "BEST_CP": {
            "MIN_AMOUNT": 1,
            "KEEP_ADDITIONAL_SCALAR": 1.0,
            "MAX_AMOUNT": 999
          },
          "BEST_IV": {
            "MIN_AMOUNT": 1,
            "KEEP_ADDITIONAL_SCALAR": 1.0,
            "MAX_AMOUNT": 999,
            "IGNORE_BELOW": 50
          }
        },
        "SCORE_METHOD": "IV",
        "SCORE_METHOD_FANCY": {
          "WEIGHT_IV": 0.5,
          "WEIGHT_LVL": 0.5
        }
      },
      "MIN_ITEMS": {
        "ITEM_POTION": 0,
        "ITEM_SUPER_POTION": 0,
        "ITEM_HYPER_POTION": 0,
        "ITEM_MAX_POTION": 100,
        "ITEM_POKE_BALL": 100,
        "ITEM_GREAT_BALL": 100,
        "ITEM_ULTRA_BALL": 100,
        "ITEM_RAZZ_BERRY": 50,
        "ITEM_REVIVE": 0,
        "ITEM_MAX_REVIVE": 100
      },
      "NEEDY_ITEM_FARMING": {
        "ENABLE": false,
        "POKEBALL_CONTINUE_THRESHOLD": 50,
        "POKEBALL_FARM_THRESHOLD": 10,
        "FARM_IGNORE_POKEBALL_COUNT": false,
        "FARM_IGNORE_GREATBALL_COUNT": false,
        "FARM_IGNORE_ULTRABALL_COUNT": false,
        "FARM_IGNORE_MASTERBALL_COUNT": true,
        "FARM_OVERRIDE_STEP_SIZE": -1
      },
      "CONSOLE_OUTPUT": {
        "LIST_POKEMON_BEFORE_CLEANUP": true,
        "LIST_INVENTORY_BEFORE_CLEANUP": true
      }
    },
    {
      "auth_service": "ptc",
      "username": "someusername",
      "password": "password",
      "location": "University of Southern California, Los Angeles, CA",
      "BEHAVIOR": {
        "USE_GOOGLE": false
      }
    }
  ],
  "defaults": {
      "_info": "copy values to this section to use them for all accounts",
      "_info2": "account settings will always override defaults"
  }
}`

**Comment by infinitewarp** [comment] 2016-08-08 05:39
protip: using triple-backtick (```) on the line immediately above and immediately below a chunk of code will format it nicely like this

```
this is code
this keeps it in a block
no mater how long one of the lines issssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
```

**Comment by freakyfreak87** [comment] 2016-08-08 11:34
Okay thank you, I ran the bot last night for over 5 hours, and nothing evolved lol, I have over 600+ candy sitting, I'll redownload the git when I get home today

**Comment by s-amine** [comment] 2016-08-08 12:21
The same problem here, it releases but never evolves.

**Comment by freakyfreak87** [comment] 2016-08-08 15:46
Glad I'm not the only one then lol

**Comment by infinitewarp** [comment] 2016-08-08 17:16
I suspect we're missing some data here. So, I'll add some verbose logging to show all the conditions during the decision-making process.

**Comment by infinitewarp** [comment] 2016-08-08 18:12
I just merged some extra logging into the develop branch. You should now see lines like this when the code decides if it should evolve your pokemon before releasing them:

```
[ INFO] Not evolving Kakuna because you have 2 but need more than 2.
[ INFO] Pidgey can evolve? True! Need candy: 12. Have candy: 787. Favorite? False. In keep list? False. In evolution list? True.
[ INFO] Evolving pokemon: Type: Pidgey CP: 370, IV: 42.22, Lvl: 23.0, LvlWild: 23.0, MaxCP: 427, Score: 370, IV-Norm.: 36
[ INFO] Evolved to Type: Pidgeotto CP: 701, IV: 42.22, Lvl: 23.0, LvlWild: 23.0, MaxCP: 808, Score: 701, IV-Norm.: 37
[ INFO] Not evolving Pidgeotto because you have 2 but need more than 2.
[ INFO] Not evolving Pidgeot because you have 2 but need more than 2.
[ INFO] Rattata can evolve? False! Need candy: 25. Have candy: 23. Favorite? False. In keep list? False. In evolution list? True.
[ INFO] Scyther can evolve? False! Need candy: None. Have candy: 153. Favorite? False. In keep list? False. In evolution list? False.
```

Please update, look at your output, and report back with what you find for pokemon that you believe *should* be evolving but aren't.

**Comment by stolencatkarma** [comment] 2016-08-08 20:41
'''
2016-08-08 16:37:55,173 [    pgoapi] [ INFO] Venomoth can evolve? False! Need candy: None. Have candy: 249. Favorite? False. In keep list? False. In evolution list? False.
'''

this should evolve but doesn't

**Comment by stolencatkarma** [comment] 2016-08-08 20:47
everything seems good here. working as intended

` pgoapi] [ INFO] Pidgey can evolve? True! Need candy: 12. Have candy: 1374. Favorite? False. In keep list? False. In evolution list? True.
2016-08-08 16:46:20,970 [    pgoapi] [ INFO] Evolving pokemon: Type: Pidgey CP: 389, IV: 48.89, Lvl: 24.0, LvlWild: 24.0, MaxCP: 531, Score: 38.4176946912, IV-Norm.: 38
2016-08-08 16:46:22,060 [    pgoapi] [ INFO] Evolved to Type: Pidgeotto CP: 734, IV: 48.89, Lvl: 24.0, LvlWild: 24.0, MaxCP: 1002, Score: 38.3827896272, IV-Norm.: 38
2016-08-08 16:46:23,842 [    pgoapi] [ INFO] Not evolving Pidgeotto because you have 1 but need more than 1.
2016-08-08 16:46:23,843 [    pgoapi] [ INFO] Not evolving Pidgeot because you have 1 but need more than 1.
2016-08-08 16:46:23,843 [    pgoapi] [ INFO] Rattata can evolve? True! Need candy: 25. Have candy: 2625. Favorite? False. In keep list? False. In evolution list? True.
2016-08-08 16:46:23,843 [    pgoapi] [ INFO] Evolving pokemon: Type: Rattata CP: 143, IV: 22.22, Lvl: 11.0, LvlWild: 11.0, MaxCP: 425, Score: 24.4191783213, IV-Norm.: 24
2016-08-08 16:46:24,932 [    pgoapi] [ INFO] Evolved to Type: Raticate CP: 391, IV: 22.22, Lvl: 11.0, LvlWild: 11.0, MaxCP: 1165, Score: 27.0052860072, IV-Norm.: 27
2016-08-08 16:46:27,192 [    pgoapi] [ INFO] Not evolving Raticate because you have 1 but need more than 1.
2016-08-08 16:46:27,193 [    pgoapi] [ INFO] Not evolving Spearow because you have 1 but need more than 1.
2016-08-08 16:46:27,193 [    pgoapi] [ INFO] Fearow can evolve? False! Need candy: None. Have candy: 229. Favorite? False. In keep list? False. In evolution list? False.
2016-08-08 16:46:27,193 [    pgoapi] [ INFO] Not evolving Ekans because you have 1 but need more than 1.
`

**Comment by freakyfreak87** [comment] 2016-08-08 21:33
By one, doors it mean one pokemon? Why would I need more than one before it will evolve any? I am not home atm, but atm with it recycling all my pokemon before evolving all I ever have is one lol

**Comment by infinitewarp** [comment] 2016-08-08 23:36
If you are referring to the lines that say "need more than x", where x is 2 in this example:
```
[ INFO] Not evolving Kakuna because you have 2 but need more than 2.
```
That's because in my case I have my `MIN_SIMILAR_POKEMON ` config set to 2 and we don't want to evolve away your minimum number of preserved pokemon.

**Comment by freakyfreak87** [comment] 2016-08-09 00:14
Downloaded repo again, ran requirements.txt upgrade and requirenets-ci.txt and am running bot, and its still not coming across any evolve text on my end =\ blah lol

**Comment by infinitewarp** [comment] 2016-08-09 00:27
FWIW, `requirements-ci.txt` is only necessary for developers and CI (see: [Travis CI](https://travis-ci.org/j-e-k/poketrainer)) to run the build jobs (tox, flake8, etc). Probably doesn't hurt to install them as a casual user, but you're not getting any benefits from them either. :)

**Comment by freakyfreak87** [comment] 2016-08-09 00:29
im so lost atm lol trying to watch the window like a hawk to see if it evolves, but usually at the end of the cycle when it list my pokemon and egg incubation status, it just recycles pokemon and isnt evolving, im sad lol

**Comment by freakyfreak87** [comment] 2016-08-09 00:37
'''
2016-08-08 19:30:15,657 [    pgoapi] [ INFO] Nearby Pokemon: Pidgey
2016-08-08 19:30:16,627 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Pidgey CP: 0, IV: 0.00, Lvl: 1.0, LvlWild: 0.0, MaxCP: 14, Score: 0, IV-Norm.: -0
2016-08-08 19:30:17,641 [    pgoapi] [ INFO] Catching Pokemon: Type: Pidgey CP: 23, IV: 17.78, Lvl: 2.0, LvlWild: 2.0, MaxCP: 15, Score: 23, IV-Norm.: 21
2016-08-08 19:30:17,641 [    pgoapi] [ INFO] Attempting catch with POKE_BALL at 100.00% chance. Try Number: 1
2016-08-08 19:30:19,079 [    pgoapi] [ INFO] Caught Pokemon:  Type: Pidgey CP: 23, IV: 17.78, Lvl: 2.0, LvlWild: 2.0, MaxCP: 15, Score: 23, IV-Norm.: 21
'''

'''
2016-08-08 19:30:33,799 [    pgoapi] [ INFO] Recycling 1 RAZZ_BERRY(s)
2016-08-08 19:30:35,142 [    pgoapi] [ INFO] RAZZ_BERRY(s) recycled successfully. New count: 50
2016-08-08 19:30:36,657 [    pgoapi] [ INFO] Recycling 3 POKE_BALL(s)
2016-08-08 19:30:37,642 [    pgoapi] [ INFO] POKE_BALL(s) recycled successfully. New count: 100
2016-08-08 19:30:39,142 [    pgoapi] [ INFO] Recycling 1 ULTRA_BALL(s)
2016-08-08 19:30:40,127 [    pgoapi] [ INFO] ULTRA_BALL(s) recycled successfully. New count: 100
2016-08-08 19:30:41,627 [    pgoapi] [ INFO] Recycling 1 SUPER_POTION(s)
2016-08-08 19:30:42,627 [    pgoapi] [ INFO] SUPER_POTION(s) recycled successfully. New count: 0
2016-08-08 19:30:44,127 [    pgoapi] [ INFO] Inventory has 585/650 items
2016-08-08 19:30:45,111 [    pgoapi] [ INFO] Player Inventory after cleanup: PokeBalls: 100, GreatBalls: 100, MasterBalls: 0, UltraBalls: 100
 Potion: 0, Super Potion: 0, Max Potion 91, Hyper Potion 0, Lucky Eggs 8, Razz Berries 50
'''

'''
2016-08-08 19:30:45,127 [    pgoapi] [ INFO] Type: Jolteon CP: 1695, IV: 93.33, Lvl: 28.0, LvlWild: 28.0, MaxCP: 1923, Score: 93.6820119977, IV-Norm.: 94
Type: Exeggutor CP: 1046, IV: 93.33, Lvl: 12.5, LvlWild: 11.0, MaxCP: 2656, Score: 93.1590842214, IV-Norm.: 93
Type: Dratini CP: 608, IV: 93.33, Lvl: 22.0, LvlWild: 22.0, MaxCP: 878, Score: 93.1000724625, IV-Norm.: 93
Type: Vaporeon CP: 1671, IV: 91.11, Lvl: 21.0, LvlWild: 21.0, MaxCP: 2526, Score: 91.9511638578, IV-Norm.: 92
Type: Abra CP: 435, IV: 93.33, Lvl: 26.0, LvlWild: 26.0, MaxCP: 531, Score: 91.8371095059, IV-Norm.: 92
Type: Dragonite CP: 2821, IV: 91.11, Lvl: 28.5, LvlWild: 8.0, MaxCP: 3142, Score: 91.6706407122, IV-Norm.: 92
Type: Flareon CP: 588, IV: 91.11, Lvl: 8.0, LvlWild: 8.0, MaxCP: 2366, Score: 90.9928445691, IV-Norm.: 91
Type: Magmar CP: 1558, IV: 88.89, Lvl: 24.5, LvlWild: 20.0, MaxCP: 2020, Score: 88.7617248519, IV-Norm.: 89
Type: Exeggutor CP: 1985, IV: 84.44, Lvl: 24.0, LvlWild: 21.0, MaxCP: 2627, Score: 84.8542475891, IV-Norm.: 85
Type: Dratini CP: 488, IV: 82.22, Lvl: 18.0, LvlWild: 18.0, MaxCP: 861, Score: 84.6254122197, IV-Norm.: 85
Type: Victreebel CP: 1690, IV: 82.22, Lvl: 24.0, LvlWild: 17.0, MaxCP: 2236, Score: 82.2058662972, IV-Norm.: 82
Type: Flareon CP: 2223, IV: 80.00, Lvl: 30.5, LvlWild: 22.0, MaxCP: 2333, Score: 81.3122278827, IV-Norm.: 81
Type: Vaporeon CP: 1841, IV: 73.33, Lvl: 23.5, LvlWild: 22.0, MaxCP: 2487, Score: 80.6201008055, IV-Norm.: 81
Type: Snorlax CP: 1342, IV: 75.56, Lvl: 15.5, LvlWild: 14.0, MaxCP: 2749, Score: 80.2622120762, IV-Norm.: 80
Type: Poliwrath CP: 2166, IV: 77.78, Lvl: 32.5, LvlWild: 23.0, MaxCP: 2201, Score: 78.0608678415, IV-Norm.: 78
Type: Snorlax CP: 2534, IV: 71.11, Lvl: 29.5, LvlWild: 29.0, MaxCP: 2728, Score: 74.47476469, IV-Norm.: 74
Type: Vileplume CP: 1223, IV: 71.11, Lvl: 18.0, LvlWild: 18.0, MaxCP: 2158, Score: 68.6690657517, IV-Norm.: 69
Type: Exeggutor CP: 1617, IV: 66.67, Lvl: 20.0, LvlWild: 20.0, MaxCP: 2567, Score: 68.4962360406, IV-Norm.: 68
Type: Vaporeon CP: 1672, IV: 62.22, Lvl: 22.0, LvlWild: 22.0, MaxCP: 2413, Score: 59.7606438229, IV-Norm.: 60
Type: Pidgey CP: 23, IV: 17.78, Lvl: 2.0, LvlWild: 2.0, MaxCP: 486, Score: 20.8124174571, IV-Norm.: 21
2016-08-08 19:30:45,204 [    pgoapi] [ INFO] Incubating 5.0km egg, 1.77km done
2016-08-08 19:30:45,220 [    pgoapi] [ INFO] Releasing pokemon: Type: Pidgey CP: 23, IV: 17.78, Lvl: 2.0, LvlWild: 2.0, MaxCP: 486, Score: 20.8124174571, IV-Norm.: 21
2016-08-08 19:30:46,292 [    pgoapi] [ INFO] Successfully Released Pokemon Type: Pidgey CP: 23, IV: 17.78, Lvl: 2.0, LvlWild: 2.0, MaxCP: 486, Score: 20.8124174571, IV-Norm.: 21
'''

**Comment by infinitewarp** [comment] 2016-08-09 02:07
Are you sure your running on the develop branch? You should have *something* new in there between the `[ INFO] Incubating` and `[ INFO] Releasing pokemon` messages.

**Comment by freakyfreak87** [comment] 2016-08-09 02:49
grabbed the master on accident, downloaded the develop branch and altered with my normal settings and it's evolving now lol.

**Closed** 2016-08-10 03:34 UTC
