### ISSUE TITLE
[ERROR] In the CMD

### ISSUE THREAD

**Issue by Alexey2532** [j-e-k/poketrainer#224] opened 2016-07-28 21:43 UTC
2016-07-28 23:41:01,940 [    pgoapi] [ERROR] Error in pokemon encounter Pokemon instance has no attribute '__getitem__'

Help plz.

**Comment by j-e-k** [comment] 2016-07-29 16:26
This should be fixed on develop, it is caused by bad server responses and soft bans...

**Closed by j-e-k** 2016-07-29 16:26 UTC
